apiVersion: argoproj.io/v1alpha1			              # api 버전
kind: Workflow 					                            # controller 종류: 워크플로우
metadata:
  generateName: 01-hello-world-			                # 생성할 워크플로우 이름
spec:
  entrypoint: ws					                          # 플로우 스타팅 POD
  templates:
  - name: ws              				                  # POD 이름: ws
    container:
      image: docker/whalesay				                # whalesay 라고 하는 도커허브 이미지 사용
      command: [cowsay]
      args: ["hello world! hanjoo's 1st flow Job!"]