apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 06-scripts-
spec:
  entrypoint: script-example

  templates:
  - name: script-example
    steps:
    - - name: generate
        template: gen-random-int-python
    - - name: print
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate.outputs.result}}"  

  - name: gen-random-int-python
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(1, 100)
        print(i)

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo result was: {{inputs.parameters.message}}"]