apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 07-output-parameter-
spec:
  entrypoint: output-parameter

  templates:
  - name: output-parameter
    steps:
    - - name: generate-parameter
        template: ws
    - - name: consume-parameter
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate-parameter.outputs.parameters.param}}"

  - name: ws
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["echo -n Hell!! POSTECH!!! > /tmp/hellpos.txt"] 
    outputs:
      parameters:
      - name: param
        valueFrom:
          path: /tmp/hellpos.txt

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]