apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 11-recursive-

spec:
  entrypoint: coinflip

  templates:
  - name: coinflip
    steps:
    # 동전 던지기
    - - name: flip-coin
        template: flip-coin
    # 병렬 결과 계산
    - - name: heads     # "heads" 일때 head POD 호출 -> 종료
        template: heads
        when: "{{steps.flip-coin.outputs.result}} == heads"
      - name: tails     # "tails" 일때 다시 시작
        template: coinflip
        when: "{{steps.flip-coin.outputs.result}} == tails"

  - name: flip-coin
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)

  - name: heads
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"it was heads\""]