apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 12-exit-handlers-

spec:
  entrypoint: intentional-fail

  onExit: exit-handler

  templates:
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 0"]
      # args: ["echo intentional failure; exit 1"] # 의도적으로 fail 시킴

  - name: exit-handler      # Java 예외처리에서 finally 개념 (Step으로 연결시키지 않아도 무조건 실행됨)
    steps:
    - - name: notify
        template: send-email
      - name: celebrate
        template: celebrate
        when: "{{workflow.status}} == Succeeded"
      - name: cry
        template: cry
        when: "{{workflow.status}} != Succeeded"

  - name: send-email
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo send e-mail: {{workflow.name}} {{workflow.status}}"]
  
  - name: celebrate
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo ^^"]
  
  - name: cry
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo T_T"]

  