apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 16-sidecar-

spec:
  entrypoint: sidecar-nginx

  templates:
  - name: sidecar-nginx
    container:
      image: appropriate/curl
      command: [sh, -c]
      args: ["until `curl -G 'http://127.0.0.1/' >& /tmp/out`; do echo sleep && sleep 1; done && cat /tmp/out"]
    sidecars:
    - name: nginx
      image: nginx:1.13