apiVersion: argoproj.io/v1alpha1

kind: Workflow

metadata:
  generateName: 02-parameters-

spec:
  entrypoint: ws
  arguments:
    parameters:
    - name: message
      value: hello world

  templates:                                      # 템플릿 정의
  - name: ws
    inputs:
      parameters:
      - name: message                             # message 라는 파라미터 선언
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]     # message 라는 파라미터에 arg 값 입력
