apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 04-dag-diamond-
spec:
  entrypoint: diamond
  
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: Hello}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: POSTECH}]
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: TMAX}]
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: Goodbye!!!!!!!!!!!!!!!}]
