apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 08-1-loops-
spec:
  entrypoint: loop-example

  templates:
  - name: loop-example
    steps:
    - - name: print-message
        template: ws
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems:              # whalesay의 message <- value = item 1, item 2, ...
        - Goodbye POSTECH       # item 1
        - Goodbye Tmax          # item 2

  - name: ws
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]