apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 10-retry-backoff-

spec:
  entrypoint: retry-backoff

  templates:
  - name: retry-backoff
    retryStrategy:
      limit: 10
      retryPolicy: "Always" # Default: "OnFailure" (이외: "OnError")
      backoff:
        duration: "1"       # Default: 초 (이외 예제: "2m", "6h", "1d", ...)
        factor: 2
        maxDuration: "1m"   # Default: 초 (이외 예제: "2m", "6h", "1d", ...)
    container:
      image: python:alpine3.6
      command: ["python", -c]
      args: ["import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)"]  # 0, 1, 1 중 랜덤하게 하나 뽑음 -> exit 값 1 이면 비정상 종료(fail), 0 이면 정상 종료(success)