apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 13-timeouts-

spec:
  entrypoint: sleep

  templates:
  - name: sleep
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo sleeping for 1m; sleep 60; echo done"]
    activeDeadlineSeconds: 10           # 10초 후 강제 정지