apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ml-01-basic-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0, pipelines.kubeflow.org/pipeline_compilation_time: '2020-09-22T15:27:11.620973',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Simple Machine Learning
      pipeline", "name": "ML-01-basic"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0}
spec:
  entrypoint: ml-01-basic
  templates:
  - name: ml-01-basic
    dag:
      tasks:
      - {name: mnist-kfp, template: mnist-kfp}
  - name: mnist-kfp
    container: {image: 'hanjoo8821/mnist:basic'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
