apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kfp-04-exit-handler-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0, pipelines.kubeflow.org/pipeline_compilation_time: '2020-09-17T16:14:39.608254',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "cf. Java fianlly", "name":
      "kfp-04-exit handler"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0}
spec:
  entrypoint: kfp-04-exit-handler
  templates:
  - name: exit-handler-1
    dag:
      tasks:
      - {name: flip-coin, template: flip-coin}
      - name: print-2
        template: print-2
        dependencies: [flip-coin]
        arguments:
          parameters:
          - {name: flip-coin-output, value: '{{tasks.flip-coin.outputs.parameters.flip-coin-output}}'}
  - name: flip-coin
    container:
      args: ['python -c "import random; result = ''heads'' if random.randint(0,1)
          == 0 else ''tails''; print(result)" | tee /tmp/output']
      command: [sh, -c]
      image: python:alpine3.6
    outputs:
      parameters:
      - name: flip-coin-output
        valueFrom: {path: /tmp/output}
      artifacts:
      - {name: flip-coin-output, path: /tmp/output}
  - name: kfp-04-exit-handler
    dag:
      tasks:
      - {name: exit-handler-1, template: exit-handler-1}
  - name: print
    container:
      command: [echo, Exit]
      image: alpine:3.6
  - name: print-2
    container:
      command: [echo, '{{inputs.parameters.flip-coin-output}}']
      image: alpine:3.6
    inputs:
      parameters:
      - {name: flip-coin-output}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
  onExit: print
