apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kfp-10-pipeline-with-sidecar-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0, pipelines.kubeflow.org/pipeline_compilation_time: '2020-09-22T15:21:55.478486',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Add a sidecar to an operation.",
      "inputs": [{"default": "10", "name": "sleep_sec", "optional": true, "type":
      "Integer"}], "name": "kfp-10-pipeline_with_sidecar"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0}
spec:
  entrypoint: kfp-10-pipeline-with-sidecar
  templates:
  - name: download
    container:
      args: ['sleep {{inputs.parameters.sleep_sec}}; wget localhost:5678 -O /tmp/results.txt']
      command: [sh, -c]
      image: busybox:latest
    inputs:
      parameters:
      - {name: sleep_sec}
    outputs:
      parameters:
      - name: download-downloaded
        valueFrom: {path: /tmp/results.txt}
      artifacts:
      - {name: download-downloaded, path: /tmp/results.txt}
    sidecars:
    - args: [-text="This is a sidecar replying service"]
      image: hashicorp/http-echo:latest
      name: echo
  - name: echo
    container:
      args: ['echo {{inputs.parameters.download-downloaded}}']
      command: [sh, -c]
      image: library/bash
    inputs:
      parameters:
      - {name: download-downloaded}
  - name: kfp-10-pipeline-with-sidecar
    inputs:
      parameters:
      - {name: sleep_sec}
    dag:
      tasks:
      - name: download
        template: download
        arguments:
          parameters:
          - {name: sleep_sec, value: '{{inputs.parameters.sleep_sec}}'}
      - name: echo
        template: echo
        dependencies: [download]
        arguments:
          parameters:
          - {name: download-downloaded, value: '{{tasks.download.outputs.parameters.download-downloaded}}'}
  arguments:
    parameters:
    - {name: sleep_sec, value: '10'}
  serviceAccountName: pipeline-runner
