apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kfp-01-sequential-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0, pipelines.kubeflow.org/pipeline_compilation_time: '2020-09-17T10:50:13.454000',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Coin Flip example : step.",
      "name": "kfp-01-sequential"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0}
spec:
  entrypoint: kfp-01-sequential
  templates:
  - name: flip-coin
    container:
      args: ['python -c "import random; result = ''heads'' if random.randint(0,1)
          == 0 else ''tails''; print(result)" | tee /tmp/output']
      command: [sh, -c]
      image: python:alpine3.6
    outputs:
      parameters:
      - name: flip-coin-output
        valueFrom: {path: /tmp/output}
      artifacts:
      - {name: flip-coin-output, path: /tmp/output}
  - name: kfp-01-sequential
    dag:
      tasks:
      - {name: flip-coin, template: flip-coin}
      - name: print
        template: print
        dependencies: [flip-coin]
        arguments:
          parameters:
          - {name: flip-coin-output, value: '{{tasks.flip-coin.outputs.parameters.flip-coin-output}}'}
  - name: print
    container:
      command: [echo, '{{inputs.parameters.flip-coin-output}}']
      image: alpine:3.6
    inputs:
      parameters:
      - {name: flip-coin-output}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
