apiVersion: v1
kind: ReplicationController
metadata:
  name: ws-rc
spec:
  replicas: 3
  selector:
    app: hello-node
  template:
    metadata:
      name: ws-pod
      labels:
        app: hello-node
    spec:
      containers:
      - name: ws-con
        image: hanjoo8821/ws-nodejs:ex
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ws-svc
spec:
  type: LoadBalancer
#  type: NodePort
#  type: ClusterIp
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: hello-node