apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kfp-09-env-example-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0, pipelines.kubeflow.org/pipeline_compilation_time: '2020-09-18T16:47:57.990826',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Use enviroment variables.",
      "name": "kfp-09-Env example"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0}
spec:
  entrypoint: kfp-09-env-example
  templates:
  - name: kfp-09-env-example
    dag:
      tasks:
      - {name: print, template: print}
  - name: print
    container:
      command: [sh, -c, echo $EX1]
      env:
      - {name: EX1, value: ENV variable - Tmax HyperData}
      image: alpine:3.6
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
