apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  containers:
  - name: con-test
    image: hanjoo8821/jdbc-tibero:null
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: [sh, -c]
    args: ['java -cp "./JdbcAgentEx-basic.jar:./tibero6jdbc-1.0.jar" local.hanjoo.JdbcAgent "$id" "$pw"']