apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ml-02-artifact-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0, pipelines.kubeflow.org/pipeline_compilation_time: '2020-09-21T14:02:17.479742',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Simple Machine Learning
      pipeline with artifacts", "name": "ML-02-artifact"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.0}
spec:
  entrypoint: ml-02-artifact
  templates:
  - name: ml-02-artifact
    dag:
      tasks:
      - {name: mnist-kfp, template: mnist-kfp}
  - name: mnist-kfp
    container: {image: 'hanjoo8821/mnist:artifact'}
    outputs:
      artifacts:
      - {name: mlpipeline-metrics, path: /mlpipeline-metrics.json}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
